FROM node:18-alpine as builder

WORKDIR /app

COPY . .

RUN yarn

RUN yarn run build

RUN yarn install --production --ignore-scripts --prefer-offline


FROM node:18-alpine

WORKDIR /app

EXPOSE 3000

COPY package.json .

COPY --from=builder /app /app

CMD ["yarn", "run", "start:prod"]